# Generated by Django 5.0 on 2023-12-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('contact', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
