# Generated by Django 5.0 on 2023-12-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='roll_no',
            new_name='rollno',
        ),
    ]
