# Generated by Django 5.0 on 2023-12-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_details_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='testing',
            field=models.IntegerField(default=False),
        ),
    ]
