# Generated by Django 5.0 on 2023-12-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_details_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='score',
            field=models.IntegerField(default=False),
        ),
    ]
